### PR TITLE
Add mybinder

### PR DESCRIPTION
**Pull request by jan-janssen**
With mybinder it is possible to run DAMASK simulation directly in the browser using a Docker container running in a public cloud and the DAMASK conda package for installing DAMASK: 
[Binder](https://mybinder.org/v2/gh/jan-janssen/DAMASK_workflows/master)

### CODE REVIEW

**Comment by jan-janssen** [comment]
I previously created a similar example for the old DAMASK version https://github.com/jan-janssen/damask-example

**Comment by vitesh13** [comment]
Thanks for reminding Jan about this. Its good then we can carry over from that example.
I had a small discussion with Markus and we thought it would be good to show a basic DAMASK workflow status quo, what is missing and then discuss how to carry out further improvements.

**Comment by sharanroongta** [comment]
Thanks Jan. With your previous example I think it should be easy to implement the new changes in pre and post processing.

**Comment by vitesh13** [comment]
Hi Jan I tried out the binder link and it gave me an error loading the jan-janssen/DAMASK_workflows/master

Error log: Could not resolve ref for gh:jan-janssen/DAMASK_workflows/master. Double check your URL.

How make it work with binder?

**Comment by jan-janssen** [comment]
I remove the fork here is the link for your repository:
[Binder](https://mybinder.org/v2/gh/vitesh13/DAMASK_workflows/master)

**Comment by vitesh13** [comment]
Hi Jan,

I was able to launch the binder (though it takes quite a bit of time to load)
I added some example files to run on the binder. But, now I am not sure about how the simulation should run? 
In your example case, it seems the command DAMASK_spectral runs directly in the notebook. 

I tried the same thing once the binder was launched. But I get the error that it doesnt recognise DAMASK_spectral.

I guess I am missing something.

**Comment by jan-janssen** [comment]
Can you try using `DAMASK_grid` rather than `DAMASK_spectral`

**Comment by vitesh13** [comment]
> Can you try using `DAMASK_grid` rather than `DAMASK_spectral`

Yes this worked. Thanks.

**Pull request merged**
