### PR TITLE
Add post processing tools

### PR DESCRIPTION
**Pull request by jan-janssen**
But `seeds_fromRandom` throws an error

### CODE REVIEW

**Comment by jan-janssen** [comment]
5C226FE3-EA52-431B-9C7E-F57587E37CAF

**Comment by vitesh13** [comment]
Thanks for trying it out. I will merge it and have a look. This script works without any error on the workstations, so this is quite strange.

**Comment by vitesh13** [comment]
I also had a small discussion with Martin about this. He said that these extra processing scripts will also be removed soon. So if this doesnt work out, we can just wait for the python class to get modified.

**Comment by sharanroongta** [comment]
I believe it fails because Table class has changed (I don't know which version runs on this, is it a mirror of the updated development in github?). table.to_ASCII is table.save now.

**Comment by jan-janssen** [comment]
It is the 3.0.0 alpha release.

**Comment by vitesh13** [comment]
It is strange because after yesterdays pull request, the binder refers to the development version of the mirror branch right?

**Comment by sharanroongta** [comment]
The error indicates that it used the release alpha version..but it is so strange. I checked both the scripts (seeds_fromRandom and the Table class) of the release version and it is consistent..
Need to look properly. I shall try

**Comment by jan-janssen** [comment]
I updated it in https://github.com/vitesh13/DAMASK_workflows/pull/5

**Pull request merged**
